# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: beta-xcode6.1

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "HKSKaZZXMwt7kF7jLYbFy4QZ1KaV6u2fLCDlzSHGDHYV3gkadgkkvWltpTiaDCmgP8SvGJWVVMwVjGMjhi2QEsjNzq1WAsKE+MOMzK9QkUPvH5gmIAcfU/apDvxzFhwEKB5DgMxuOKyABaey64DohSDbyMuXmTxBtuPcjp0tECe3UxQtrVEg7GOOQzNPWVqMFXPOJrQX4Xszc/j3R2Fzp73FOVVKoJyHCih/1q7TnoD7pyjODDCwJR2RAOmatsBN1AwqBDV6bUXTxf1VqGrZgupLwxr82+e29wT4imYfF9Vo/OsWGqH8rFfJaIWfS23pmwKuiWT1dgqCX1/8FlOFW5t5eY/QVTsjvGjMRHMeG2DH2pSU06Gym5WyNvHtzuaEjvcakxRXVNowgwxDfV+H5tLxuGa7TCf9X1Cv/Y5wE2Iyk8oa8ydHj5+nXd1/HAMA6Fa+gthfhRzTCqyM7gnkY/huzBcmTKg7CgU9KBRPUbMqJ/s3RB1LOwrvs3f2FQs4xA+N5IB1g2cTc/z75YWYmUj/FCDgvqE3bCS1tJaSuNf2eXdTM9QZZBaqe9lhKKLTXmQdr881OlS9XnjOsbFCoF4OhzLGkaX0Hkvsg/L+9lbmkl8UMBup2VzMwgrS5Gy3hd+E/KlbNxxS/5qDpr25r1N2q6L/Z/6ECB/2FuzWQ7s="


before_install:
    # Remove homebrew.
    - brew remove --force $(brew list)
    - brew cleanup -s
    - rm -rf $(brew --cache)

install:
    - |
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      source /Users/travis/miniconda3/bin/activate root
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
