travis:
  secure:
    BINSTAR_TOKEN: XcJ1Q7nyrbVpI81/dnx0B6Xt6Cf7Po05+/QLLq+LOTZR6whdn08ZGwYHEn4eyfaNrdDvrgyY03Ku0BZ9j0mNuh2RGPrL9RolRY2fkXNi076jJ/SB+FaXjFgGNA4tZ/j79K9yvRPacdIWdAbU7u7of8FhBa3h4QYR/P6KoKSmD3WYsvJiom9qNHiu1k1GAGaTOszvN4CNE3drNCxjTxD0FxOghTseGlzocCI887brh5f+E5CkvD6MUfF5ni4YQ8g/P/Ahgfatz6qzChj4jCpZS/sM2+ovjAko7kPSj0sUpyfAQfCXd89zOot7IcsZ+U1AzVzvc6k1GkeJ84b8o/fJ8qVZDw92RR4MBxcgOFrqV7SSd+rWedgLTF6EG7WPEk6NHc15tvbBPZTG8AbTPguKPei6XRyRG51n+IhDoWA/124YvjVukFHLCsm8OODo4fXr3WMm6EtqVFjLSmuHYNwCbX1QgtftGlTl64oqqw6me6rulQ3ZE+lab8KAQbC84QP7GvfzzHrhPsiRRFtD3BfBxHrVi/O+bJZQvfWucWhaYWyWLiG2OiLKekkChqXAEOg9pn7Q+C14FrYby1bXj7cCO5T5Jb99CyxpOP/ubkAofzXUWdYD+WqXChl8VUJKFCkM74C9FYw1/jjbHWFjXVeLKVwRpJzADAwExUPBkaHIhJ4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
