travis:
  secure:
    BINSTAR_TOKEN: HKSKaZZXMwt7kF7jLYbFy4QZ1KaV6u2fLCDlzSHGDHYV3gkadgkkvWltpTiaDCmgP8SvGJWVVMwVjGMjhi2QEsjNzq1WAsKE+MOMzK9QkUPvH5gmIAcfU/apDvxzFhwEKB5DgMxuOKyABaey64DohSDbyMuXmTxBtuPcjp0tECe3UxQtrVEg7GOOQzNPWVqMFXPOJrQX4Xszc/j3R2Fzp73FOVVKoJyHCih/1q7TnoD7pyjODDCwJR2RAOmatsBN1AwqBDV6bUXTxf1VqGrZgupLwxr82+e29wT4imYfF9Vo/OsWGqH8rFfJaIWfS23pmwKuiWT1dgqCX1/8FlOFW5t5eY/QVTsjvGjMRHMeG2DH2pSU06Gym5WyNvHtzuaEjvcakxRXVNowgwxDfV+H5tLxuGa7TCf9X1Cv/Y5wE2Iyk8oa8ydHj5+nXd1/HAMA6Fa+gthfhRzTCqyM7gnkY/huzBcmTKg7CgU9KBRPUbMqJ/s3RB1LOwrvs3f2FQs4xA+N5IB1g2cTc/z75YWYmUj/FCDgvqE3bCS1tJaSuNf2eXdTM9QZZBaqe9lhKKLTXmQdr881OlS9XnjOsbFCoF4OhzLGkaX0Hkvsg/L+9lbmkl8UMBup2VzMwgrS5Gy3hd+E/KlbNxxS/5qDpr25r1N2q6L/Z/6ECB/2FuzWQ7s=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
